### ISSUE TITLE
Expression Returns Null if ZeroLiteral or OneLiteral is used in the Expression.

### ISSUE THREAD

**Issue by gunpal5** [alethic/BoolExprNet#2]
Hi,

I was playing with the BoolExprNet. I am struggling to get it working with Zero and One inputs. It is returning null if I use Zero or One Literal in Expression. e.g.

`
var f = Not(Expression.Zero); // f is Null`

`var k = ExclusiveNotOr(Expression.One,Expression.Zero,Expression.One).Simplify(); // k is null;`

Is there any way to work  with 1 and 0?

**Comment by wasabii** [comment]
Had a weird bug. Pushing a fix.

**Comment by gunpal5** [comment]
@wasabii Thank you for quick fix. I'll check that out.

**Comment by wasabii** [comment]
1.0.9 pushed to NuGet.
